### ISSUE TITLE
unable to find install instructions for hsw-cli

### ISSUE THREAD

**Issue by gosuri** [handshake-org/handshake-org.github.io#10]
can't figure out where to grab `hsw-cli` from, any help is much appreciated!

**Comment by kilpatty** [comment]
@gosuri hsw-cli should be installed in your node bin if you run
`npm install --production` inside of the hsd directory. https://github.com/handshake-org/hsd#install

Hope that helps!

**Comment by boymanjor** [comment]
@gosuri you could also run `npm install -g hs-client`

I'm closing this for now. Feel free to re-open if the information was not sufficient. Thanks for the help @kilpatty!
