### ISSUE TITLE
Use `gh-pages` for GitHub pages

### ISSUE THREAD

**Issue by Falci** [handshake-org/handshake-org.github.io#102]
I was working on #81 and then I realised we can do some improvements in the structure of this repo.

Here's my suggestion:
First, separate source and auto generated files. Currently, the [build](https://github.com/handshake-org/handshake-org.github.io/blob/master/bin/build) generates files in the repo's root ([index.html](https://github.com/handshake-org/handshake-org.github.io/blob/master/index.html)).
The build script does a surgery for cleaning the workspace before generating new files.
We could have a single `./build` folder and use that as root for GitHub Pages.

Since the final goal is to automatise the doc generation, we could go even further and use another branch. This is a common strategy. We have a branch in which we only have the website content, all generated files, plus any other resource. No sources there.

The main advantage on having a separated branch instead of a folder is the event: when using different branches a change in master always means new/updated content and can trigger the docs generation which will push changes to a side branch

So, the first step in this direction would be to create a branch from master, named `gh-pages` and update this project settings to use that branch as source for GitHub Pages.
I can't create a PR to a non-existing branch, nor change the repo settings.

**Comment by pinheadmz** [comment]
new branch: https://github.com/handshake-org/handshake-org.github.io/tree/gh-pages
