### ISSUE TITLE
Switch IRC links from freenode -> libera

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/handshake-org.github.io#132]
This goes for handshake-web as well. I have no idea what the hell is going on over there, maybe this:

https://www.devever.net/~hl/freenode_suicide

The #handshake channel is out of control pummeled by spam, no one has Ops control, freenode is over.

**Comment by realrasengan** [comment]
Is this some kind of a joke?

**Comment by pinheadmz** [comment]
This is #handshake on freenode right now:

<img width="1069" alt="Screen Shot 2021-07-14 at 7 00 00 PM" src="https://user-images.githubusercontent.com/2084648/125703465-93321eb2-5579-4241-8474-c9cec0f048c7.png">

**Comment by pinheadmz** [comment]
@realrasengan what happened to your nick? I thought you left too or something?

`18:15 Message(401): No such nick`
