### ISSUE TITLE
Developer mailing list email is down

### ISSUE THREAD

**Issue by evbots** [handshake-org/handshake-org.github.io#22]
I have tried to subscribe to the mailing list for handshake by emailing subscribe to devs@handshake.org. I got "email account that you tried to reach does not exist" from the email server.

**Comment by evbots** [comment]
Ok. Is there a way to get logs from the past activity in the freenode #handshake channel? @hschoenburg

**Comment by tynes** [comment]
@hschoenburg bump

**Comment by hschoenburg** [comment]
@tynes going to take down the signup form. People should go to #handshake on IRC or via Telegram here https://t.me/handshake_hns or here https://hnsalliance.org

**Comment by tynes** [comment]
@hschoenburg thank you!
