### ISSUE TITLE
validateaddress RPC Updates

### ISSUE THREAD

**Issue by tynes** [handshake-org/handshake-org.github.io#30]
Updates needed in docs

This commit was merged in and updates node RPC `validateaddress`

https://github.com/handshake-org/hsd/commit/62b4de584cdabd4488d0583cd4c2b2f3e75d4a60

**Comment by boymanjor** [comment]
@tynes do you mind opening a PR for this update?

**Comment by tynes** [comment]
@boymanjor Will push up a PR adding this
