### ISSUE TITLE
Installing issue on Windows - Unable to find "bstring" directly

### ISSUE THREAD

**Issue by umetaku5** [handshake-org/handshake-org.github.io#34]
I'm trying to install Handshake into my Windows laptop seeing this page https://handshake-org.github.io/guides/win-install.html , and facing this operation problem :

$cd bstring

I can't find such directly.

**Comment by tynes** [comment]
I recommend using Linux Subsystem for Windows, things should just work.

**Comment by pinheadmz** [comment]
@umetaku5 Did you ever solve this issue? If you have more problems installing, you should open an issue at https://github.com/handshake-org/hsd or join us on telegram https://t.me/hns_tech or on the bcoin slack: https://bcoin.io/slack-signup

**Comment by boymanjor** [comment]
The windows instructions on the site have been removed. We now refer users to the [repo](https://github.com/handshake-org/hsd#install). I'm closing this for now.
