### ISSUE TITLE
Error on Windows machine

### ISSUE THREAD

**Issue by cyborg37** [handshake-org/handshake-org.github.io#5]
In trying to set this up on my Windows 10 machine, I get the following error:

$ ./bin/hsd
./bin/hsd: line 2: $'\r': command not found
./bin/hsd: line 6: $'\r': command not found
./bin/hsd: line 41: syntax error near unexpected token `$'do\r''
'/bin/hsd: line 41: `for arg in "$@"; do

**Comment by boymanjor** [comment]
The Windows instructions have been removed from the docs. Please refer to the hsd [repo]( https://github.com/handshake-org/hsd ).
