### ISSUE TITLE
Claiming a .org reserved name

### ISSUE THREAD

**Issue by freedomfighter2020** [handshake-org/handshake-org.github.io#59]
I have 4 domains that made it to the Alexa 100k list
I was able to successfully claim 2 (a .com and a .tv)
However I am getting an error message of "No RRSIG(DS) records" for the other 2 (a .org and a .info).
I've double and triple checked my set up (using Cloudflare as dns provider).
Also I see the only domains which have been claimed thus far contain no .orgs or infos.
Which leads me to believe that there is something not compatible with these TLDs.

**Comment by pinheadmz** [comment]
Correct. `.org` has insecure DNSSEC, using a key with a SHA-1 algorithm. Such keys are considered weak and are invalid in claims. Whoever manages `org` will have to resign their zone with a modern strong key for these names to be claimable on handshake.

**Comment by freedomfighter2020** [comment]
Thanks for the quick response.
RE: "Whoever manages org will have to resign their zone with a modern strong key for these names to be claimable on handshake."
Sorry this is all very foreign to me.
Do I reach out to my registrar, dns provider or will something need to be done manually?
Could you point me in the right direction to do that?
Much appreciated.

**Comment by pinheadmz** [comment]
Unfortunately the security upgrade needs to be done by the operator of `.org`: https://en.wikipedia.org/wiki/Public_Interest_Registry

**Comment by freedomfighter2020** [comment]
Wow.
Im guessing that won't be as easy as politely asking via an email.
Is there no workaround at all?
How will other .orgs/.infos be able to utilize handshake if this is the case?

**Comment by pinheadmz** [comment]
Handshake can still be utilized by anyone, the tokens are already dispersed far and wide and is an open-source permissionless network :-)

The developers decided that it would be irresponsible to allow weak cryptographic proofs to claim reserved names, and yeah unfortunately this affects many legacy name owners. DNSSEC has been around a long time but never gained good adoption. Perhaps Handshake will being around a revival in good crypto practices! There are millions of `.org` nameholders -- they could all demand their stewards use a strong zone signing key!

**Comment by pinheadmz** [comment]
Closing in favor of https://github.com/handshake-org/hsd/issues/399
