### ISSUE TITLE
How to run pseudo-airgapped hs-airdrop using Docker

### ISSUE THREAD

**Issue by benjie** [handshake-org/handshake-org.github.io#61]
Please feel free to add this as a guide to your website if you would like. I do not require attribution.

Originally posted here: https://github.com/handshake-org/hs-airdrop/issues/2#issuecomment-597579573

**DISCLAIMER**: THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

---

First, create this `Dockerfile` in an empty directory:

```Dockerfile
FROM node

RUN git clone https://github.com/handshake-org/hs-airdrop.git /hs-airdrop
WORKDIR /hs-airdrop
RUN yarn
RUN mkdir -p /root/.hs-tree-data/nonces
RUN curl -Lo /root/.hs-tree-data/tree.bin https://github.com/handshake-org/hs-tree-data/raw/master/tree.bin
RUN curl -Lo /root/.hs-tree-data/faucet.bin https://github.com/handshake-org/hs-tree-data/raw/master/faucet.bin
RUN curl -Lo /root/.hs-tree-data/proof.json https://github.com/handshake-org/hs-tree-data/raw/master/proof.json
RUN curl -Lo /root/.hs-tree-data/nonces/172.bin https://github.com/handshake-org/hs-tree-data/raw/master/nonces/172.bin
```

In that directory, run the following commands:

```bash
mkdir keys
cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pub keys
# Change the password on your SSH key
ssh-keygen -p -f keys/id_rsa

docker build -t hs-airdrop .

docker run --rm -it --network none --name no-net --volume=$(pwd)/keys:/ssh hs-airdrop bash
```

You'll now be running a non-networked container. This is not as secure as it could be if you properly air-gapped, but it's better than nothing. Inside the container you can check there's no network connectivity:

```bash
ping 8.8.8.8
```

Should give an error - so you know there's no internet. Now run the airdrop command:

```bash
./bin/hs-airdrop /ssh/id_rsa <YOUR_WALLET_ADDRESS> 0.010
```

(0.010 is the mining fee recommended by namebase.io)

You'll probably get an error about not being able to fetch the nonce; this is likely because bucket 172 above is incorrect for you. Exit the docker bash shell, edit the Dockerfile above to contain the correct bucket number (in BOTH PLACES on that final line), then run again:

```bash
docker build -t hs-airdrop .

docker run --rm -it --network none --name no-net --volume=$(pwd)/keys:/ssh hs-airdrop bash
```

Issue the `./bin/hs-airdrop` command again and hopefully this time it will work.

**Comment by pinheadmz** [comment]
ha shoot sorry, this is the repo for a new guide. I'm going to copy this issue back over to hs-airdrop

**Comment by benjie** [comment]
Ah; I just raised https://github.com/handshake-org/handshake-org.github.io/pull/63 :laughing: 

I'll leave it in your hands.

**Comment by benjie** [comment]
(Note #63 contains a few minor edits and a tiny bit of formatting.)
