### ISSUE TITLE
When to use HNS vs dollarydoos 

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/handshake-org.github.io#95]
Note the message here: https://hsd-dev.org/api-docs/#create-a-transaction

> Be careful how you enter values and fee rates!
> value and rate are expressed in subunits when using cURL or Javascript
> value and rate are expressed in WHOLE HNS when using CLI
> Watch carefully how values are entered in the examples, all examples send the same amount when executed

This is a big issue with the API -- between RPC and HTTP APIs, and then using CLI commands vs curl or JS... developers can get really screwed up.

We need a big explainer in the "intro" section at the top of the api-docs, maybe with a chart, that lays out when and where and why which unit is used for which methods. We don't want developers entering `1000000` and accidentally sending 1,000,000 HNS when they think they're just sending 1.000000 HNS !

This applies to all fee settings and value settings in transaction stuff. Probably throughout the API docs the new intro message should be linked-to for reference.

**Comment by randomlogin** [comment]
https://github.com/handshake-org/handshake-org.github.io/pull/101

**Comment by pinheadmz** [comment]
closed https://github.com/handshake-org/handshake-org.github.io/commit/93266f4388789d681abfeddceb8974a76c42898d
