### ISSUE TITLE
7,200+ HNS available in bounties for closing these issues in the API docs

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/handshake-org.github.io#96]
Updating the docs can be tedious, and requires a bunch of dependencies like ruby to build locally. These are bounties I will pay to contributors who write high-quality pull requests **that get merged**. If a task seems like more than it's worth here, leave a comment and I'll bump the bounty up. After a few weeks with no takers I may bump them anyway. These payments are coming out of my personal wallet (not from any foundation or fund) which contains funds from multiple donations I've received over the last 6 months or so. Be sure to include an HNS address in your PR comments, or you can send it to me privately: pinheadmz@gmail.com or @pinheadmz on telegram

To prevent multiple developers from colliding on projects, just leave a comment below that you are going to start working on an issue so other contributors know. If mulitple developers work on a PR together, I may split the bounty between them or (if the quality is impressive enough) just double it.

This is an experiment! I am curious to see what happens here and I really want more developers contributing to handshake-org. One of my first contributions ever to bcoin was [an overhaul to the API docs](https://github.com/bcoin-org/bcoin-org.github.io/pull/87) and it was extremely educational and helped me bootstrap into the bcoin-org team. If you are interested in contributing at all to Handshake development, this is a really good place to start.

If you have any questions or need help, contact us in the dev chat on telegram: https://t.me/hns_tech

| Issue | Bounty | closed |
|-|-|-|
| ~api-docs: bump explanation of "unconfirmed" to top / intro section #94~ | ~300 HNS~ | ✅  |
| ~remove `network` from options passed to NodeClient and WalletClient #92~ | ~600 HNS~ | ✅  |
| ~When to use HNS vs dollarydoos #95~ | ~1200 HNS~ | ✅  |
| ~remove nested address #88~ | ~300 HNS~ | ✅  |
| ~apidocs intro should explain wallet plugin/standalone #85~ | ~1200 HNS~ | ✅  |
| ~api-docs: rpc getnameresource example is outdated #83~ | ~300 HNS~ | ✅  |
| ~CI for build/deploy #81~ | ~1200 HNS~ | ✅  |
| ~wallet rpc create__ functions are missing #64~ | ~1800 HNS~ | ✅  |
| Flags in docs diverged from implementation #58 (see [comment](https://github.com/handshake-org/handshake-org.github.io/issues/58#issuecomment-768500850)) | 100 HNS ||

**Comment by pedrovitti** [comment]
Hi there, I've opened MRs for issues:

#94 (MR: https://github.com/handshake-org/handshake-org.github.io/pull/97)  
#92 (MR: https://github.com/handshake-org/handshake-org.github.io/pull/99)
#88 (MR: https://github.com/handshake-org/handshake-org.github.io/pull/100)

**Comment by randomlogin** [comment]
[Pull request](https://github.com/handshake-org/handshake-org.github.io/pull/101) for "When to use HNS vs dollarydoos #95".

**Comment by pinheadmz** [comment]
@pedrovitti thank you! You can share an HNS address here or if you'd rather be private, please post a SECRET gist from your github account and email me the link: pinheadmz@gmail.com

**Comment by pedrovitti** [comment]
MR https://github.com/handshake-org/handshake-org.github.io/pull/106 opened for issue #83.

**Comment by randomlogin** [comment]
@pedrovitti could you please indicate what else you're going to close?
For example I was planning to do #64 #85.

**Comment by pedrovitti** [comment]
Hey @randomlogin, feel free to work on those. I have nothing else planned to close for now.
